#!/usr/bin/env bash
# .foundation kernel script — configure the CONFIG block below per book.
# =============================================================================
# stage_report.sh — generate ONE dated stage-end report bundling the audit
# (drift + next-step advisor + evidence) and the coverage report (tooling usage
# + dead/orphan). Run it at every phase/stage boundary (the PROCESS-CHECK step +
# /retro) so each stage closes with a written record of: is everything followed,
# what's next, and what tooling is unused/dead. Writes a dated file under the
# logs dir.
#
# USED BY: ALL book types. A stage-end record is genre-independent. The two
# bundled scripts (audit + coverage) carry their own per-book CONFIG; this
# wrapper only needs its path tokens resolved.
#
# Usage: stage_report.sh [label]   Exit: mirrors the audit (0 clean / 1 drift).
# =============================================================================
set -uo pipefail

# ===== CONFIGURE PER BOOK (see .foundation/BOOK-TYPE-PROFILES.md) =====
LOGS_DIR="10-logs"          # e.g. 10-logs   (the dated report is written here)
ACTIVITY_LOG="10-logs/activity.jsonl"           # e.g. 10-logs/activity.jsonl
AUDIT_SH=".claude/scripts/audit.sh"          # e.g. .claude/scripts/audit.sh
COVERAGE_SH=".claude/scripts/coverage.sh"    # e.g. .claude/scripts/coverage.sh
PROCESS_STEP="00-strategy/PIPELINE.md"  # e.g. "PIPELINE Step 11c / /stage-report"  (provenance line in the report)
# =====================================================================

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
label="${1:-stage}"
day="$(date -u +%Y%m%d)"
OUT="${LOGS_DIR}/STAGE-REPORT-${day}.md"
mkdir -p "$LOGS_DIR"
arc=0
{
  echo "# STAGE REPORT — ${label} — $(date -u +%Y-%m-%dT%H:%MZ)"
  echo ""
  echo "_Generated by stage_report.sh (${PROCESS_STEP}). Bundles audit + coverage._"
  echo ""
  echo "## 1. Audit — drift, next step per chapter, evidence"
  echo '```'
  bash "$AUDIT_SH" 2>&1 || arc=1
  echo '```'
  echo ""
  echo "## 2. Coverage — tooling usage + dead/orphan"
  echo '```'
  bash "$COVERAGE_SH" 2>&1 || true
  echo '```'
  echo ""
  echo "## 3. Activity-log volume"
  if [ -f "$ACTIVITY_LOG" ]; then echo "- $(wc -l < "$ACTIVITY_LOG" | tr -d ' ') logged actions in ${ACTIVITY_LOG}"; else echo "- (activity log not yet created)"; fi
} > "$OUT"
echo "stage_report: wrote $OUT (audit exit=$arc)"
exit "$arc"
